input ShippingItem {
  id: String
  quantity: String
  seller: String
}

type Query {
  shipping(
    postalCode: String
    geoCoordinates: [String]
    country: String
    items: [ShippingItem]
  ): ShippingData
  getWishlist(email: String): GetWishlistData
  getWishListProducts(path: String): WishListProductsData
}

type Mutation {
  setWishlist(email: String, skuId: String): SetWishlistData
}
