input ShippingItem {
  id: String
  quantity: String
  seller: String
}

type Query {
  shipping(
    postalCode: String
    geoCoordinates: [String]
    country: String
    items: [ShippingItem]
  ): ShippingData
}