type GetWishlistData {
  email: String
  skuId: String
  id: String
}
type SetWishlistData {
  message: String
}
type WishListProductsData {
  referenceId: String
  productName: String
  link: String
  image: String
  price: String
}